sectors = [
    {
        "ticker": "088980",
        "name": "맥쿼리인프라",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "신탁업 및 집합투자업",
        "products": "증권투자회사",
    },
    {
        "ticker": "950160",
        "name": "코오롱티슈진",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기초 의약물질 제조업",
        "products": "골관절염 치료제",
    },
    {
        "ticker": "395400",
        "name": "SK리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "서울 중구 소재 SK서린빌딩 및 전국 116개 주유소 임대 운영",
    },
    {
        "ticker": "330590",
        "name": "롯데리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "부동산투자",
    },
    {
        "ticker": "365550",
        "name": "ESR켄달스퀘어리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "부동산투자",
    },
    {
        "ticker": "415640",
        "name": "KB발해인프라",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "신탁업 및 집합투자업",
        "products": "None",
    },
    {
        "ticker": "950210",
        "name": "프레스티지바이오파마",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "자연과학 및 공학 연구개발업",
        "products": "바이오시밀러 및 항체의약품 신약",
    },
    {
        "ticker": "451800",
        "name": "한화리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "부동산투자",
    },
    {
        "ticker": "293940",
        "name": "신한알파리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "비거주 부동산 임대 서비스업",
    },
    {
        "ticker": "001570",
        "name": "금양",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기초 화학물질 제조업",
        "products": "발포제,사카린,OPTSA,베나졸,TCA 제조",
    },
    {
        "ticker": "348950",
        "name": "제이알글로벌리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "벨기에 파이낸스 타워",
    },
    {
        "ticker": "094800",
        "name": "맵스리얼티1",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "신탁업 및 집합투자업",
        "products": "None",
    },
    {
        "ticker": "357120",
        "name": "코람코라이프인프라리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "부동산 투자 및 관리",
    },
    {
        "ticker": "448730",
        "name": "삼성FN리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "대치타워 및 에스원빌딩",
    },
    {
        "ticker": "432320",
        "name": "KB스타리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "벨기에 North Galaxy Towers, 영국 Samsung Europe HQ",
    },
    {
        "ticker": "950170",
        "name": "JTC",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "종합 소매업",
        "products": "식품류, 생활용품류, 화장품류 (사후면세업)",
    },
    {
        "ticker": "900140",
        "name": "엘브이엠씨",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "자동차 판매업",
        "products": "지주회사",
    },
    {
        "ticker": "377190",
        "name": "디앤디플랫폼리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "부동산 투자 및 관리",
    },
    {
        "ticker": "088260",
        "name": "이리츠코크렙",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "부동산투자회사",
    },
    {
        "ticker": "182400",
        "name": "엔케이맥스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기초 의약물질 제조업",
        "products": "연구용 시약, NK Vue® KIT, SuperNK",
    },
    {
        "ticker": "0030R0",
        "name": "대신밸류리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "신탁업 및 집합투자업",
        "products": "부동산 임대",
    },
    {
        "ticker": "950140",
        "name": "잉글우드랩",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 화학제품 제조업",
        "products": "화장품OEM·ODM",
    },
    {
        "ticker": "121800",
        "name": "비덴트",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "통신 및 방송 장비 제조업",
        "products": "방송용 LCD모니터",
    },
    {
        "ticker": "417310",
        "name": "코람코더원리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "서울 영등포구 여의도 소재 하나금융투자 빌딩",
    },
    {
        "ticker": "377460",
        "name": "위니아에이드",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "개인 및 가정용품 수리업",
        "products": "전자제품 소매, 물류주선, 서비스대행",
    },
    {
        "ticker": "150840",
        "name": "인트로메딕",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "의료용 기기 제조업",
        "products": "캡슐내시경, 일회용 연성내시경",
    },
    {
        "ticker": "900290",
        "name": "GRT",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 금융업",
        "products": "광학필름, 포장필름",
    },
    {
        "ticker": "174900",
        "name": "앱클론",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "의료용품 및 기타 의약 관련제품 제조업",
        "products": "항체의약품",
    },
    {
        "ticker": "208340",
        "name": "파멥신",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "의약품 제조업",
        "products": "항체치료제",
    },
    {
        "ticker": "334890",
        "name": "이지스밸류플러스리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "부동산투자, 취득, 매매, 임대",
    },
    {
        "ticker": "057880",
        "name": "푸른소나무",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "비거주 복지시설 운영업",
        "products": "의료기기",
    },
    {
        "ticker": "950130",
        "name": "엑세스바이오",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "의료용품 및 기타 의약 관련제품 제조업",
        "products": "말라리아 진단키트(RDT), HIV 진단키트(RDT)",
    },
    {
        "ticker": "404990",
        "name": "신한서부티엔디리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "부동산투자",
    },
    {
        "ticker": "016790",
        "name": "현대사료",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "동물용 사료 및 조제식품 제조업",
        "products": "양계, 양돈 배합사료",
    },
    {
        "ticker": "288330",
        "name": "파라택시스코리아",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기초 의약물질 제조업",
        "products": "펠리노-1 단백질 저해제, 오토택신 저해제",
    },
    {
        "ticker": "046070",
        "name": "코다코",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "자동차 신품 부품 제조업",
        "products": "Oil Pump, Throttle Body",
    },
    {
        "ticker": "008110",
        "name": "대동전자",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "통신 및 방송 장비 제조업",
        "products": "통신음향,전자기계기구용 플라스틱제품 제조,도매",
    },
    {
        "ticker": "068790",
        "name": "DMS",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "특수 목적용 기계 제조업",
        "products": "LCD 제조장비",
    },
    {
        "ticker": "350520",
        "name": "이지스레지던스리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "부동산투자, 취득, 매매, 임대",
    },
    {
        "ticker": "400760",
        "name": "NH올원리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "부동산투자",
    },
    {
        "ticker": "066410",
        "name": "버킷스튜디오",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "전기 통신업",
        "products": "DVD타이틀",
    },
    {
        "ticker": "033180",
        "name": "KH 필룩스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "전자부품 제조업",
        "products": "전자부품(페라이트코아,트랜스포머,데코램프) 제조/온라인정보 제공/부동산 임대",
    },
    {
        "ticker": "269620",
        "name": "시스웍",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외",
        "products": "클린룸 제어시스템, BLDC모터, 공조장치 제어기 등",
    },
    {
        "ticker": "950190",
        "name": "고스트스튜디오",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "소프트웨어 개발 및 공급업",
        "products": "캐주얼게임, 소셜카지노게임",
    },
    {
        "ticker": "151910",
        "name": "퓨처코어",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "전자부품 제조업",
        "products": "Blue Filter, IR Filter, Camera Module",
    },
    {
        "ticker": "041590",
        "name": "플래스크",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "실내건축 및 건축마무리 공사업",
        "products": "실내건축 등",
    },
    {
        "ticker": "180400",
        "name": "DXVX",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 과학기술 서비스업",
        "products": "BAC DNA CHIP",
    },
    {
        "ticker": "396690",
        "name": "미래에셋글로벌리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "부동산 임대업",
    },
    {
        "ticker": "900250",
        "name": "크리스탈신소재",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 금융업",
        "products": "합성운모 플레이크, 파우더, 테이프",
    },
    {
        "ticker": "119650",
        "name": "KC코트렐",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "일반 목적용 기계 제조업",
        "products": "전기집진기 등",
    },
    {
        "ticker": "066790",
        "name": "씨씨에스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "텔레비전 방송업",
        "products": "케이블TV서비스 및 초고속인터넷서비스",
    },
    {
        "ticker": "006490",
        "name": "인스코비",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "전기 통신업",
        "products": "시계,스마트그리드,도소매,소프트웨어개발",
    },
    {
        "ticker": "149980",
        "name": "하이로닉",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "의료용 기기 제조업",
        "products": "피부미용 의료기기",
    },
    {
        "ticker": "014200",
        "name": "광림",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "자동차용 엔진 및 자동차 제조업",
        "products": "전기공사용 특수차량 및 중량물 운반용 크레인을 생산, 판매하는 제조업체",
    },
    {
        "ticker": "338100",
        "name": "NH프라임리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "부동산 투자",
    },
    {
        "ticker": "950220",
        "name": "네오이뮨텍",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "자연과학 및 공학 연구개발업",
        "products": "면역항암제",
    },
    {
        "ticker": "448900",
        "name": "한국피아이엠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "자동차 신품 부품 제조업",
        "products": "내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)",
    },
    {
        "ticker": "222810",
        "name": "세토피아",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "1차 철강 제조업",
        "products": "보안솔루션 개발 외",
    },
    {
        "ticker": "412540",
        "name": "제일엠앤에스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "특수 목적용 기계 제조업",
        "products": "2차전지 믹싱시스템",
    },
    {
        "ticker": "001470",
        "name": "삼부토건",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "토목 건설업",
        "products": "토목공사,건축공사,포장공사,건설업,분양사업/건설자재 제조",
    },
    {
        "ticker": "222160",
        "name": "NPX",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "특수 목적용 기계 제조업",
        "products": "인쇄회로기판(PCB) 전기검사기",
    },
    {
        "ticker": "073570",
        "name": "리튬포어스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "그외 기타 제품 제조업",
        "products": "휴대폰액세서리의 제조, 판매",
    },
    {
        "ticker": "203690",
        "name": "아크솔루션스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "펄프, 종이 및 판지 제조업",
        "products": "화장품",
    },
    {
        "ticker": "003560",
        "name": "아이에이치큐",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "영화, 비디오물, 방송프로그램 제작 및 배급업",
        "products": "매니지먼트, 음반, 드라마 제작, 유료방송, 프로그램 공급, 광고대행",
    },
    {
        "ticker": "950200",
        "name": "소마젠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "그외 기타 전문, 과학 및 기술 서비스업",
        "products": "유전체 분석 서비스 (NGS, CES 등)",
    },
    {
        "ticker": "357250",
        "name": "미래에셋맵스리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "부동산 임대업",
    },
    {
        "ticker": "073640",
        "name": "테라사이언스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 금속 가공제품 제조업",
        "products": "유압용 관이음쇠",
    },
    {
        "ticker": "196300",
        "name": "HLB펩",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기초 의약물질 제조업",
        "products": "펩타이드 바이오소재 및 아미노산 펩타이드 신약",
    },
    {
        "ticker": "226360",
        "name": "KH 건설",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "토목 건설업",
        "products": "기업인수합병",
    },
    {
        "ticker": "091090",
        "name": "세원이앤씨",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "구조용 금속제품, 탱크 및 증기발생기 제조업",
        "products": "화학플랜트 설비,기계 제작(음식료,석유화학사업관련)/유공압기기 판매",
    },
    {
        "ticker": "481850",
        "name": "신한글로벌액티브리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "신탁업 및 집합투자업",
        "products": "신탁 및 집합투자",
    },
    {
        "ticker": "111870",
        "name": "KH 미래물산",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "영상 및 음향기기 제조업",
        "products": "이어폰,헤드폰,키패드",
    },
    {
        "ticker": "065650",
        "name": "하이퍼코퍼레이션",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기계장비 및 관련 물품 도매업",
        "products": "음반재킷 제작",
    },
    {
        "ticker": "052670",
        "name": "제일바이오",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "의약품 제조업",
        "products": "동물사료첨가제",
    },
    {
        "ticker": "290720",
        "name": "푸드나무",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "무점포 소매업",
        "products": "None",
    },
    {
        "ticker": "099520",
        "name": "DGI",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "영상 및 음향기기 제조업",
        "products": "DVR,유선통신기기 제조,무역/소프트웨어 자문,연구개발,기술용역",
    },
    {
        "ticker": "245620",
        "name": "EDGC",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "자연과학 및 공학 연구개발업",
        "products": "유전체 분석 진단 서비스",
    },
    {
        "ticker": "900340",
        "name": "윙입푸드",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 금융업",
        "products": "육가공 제품",
    },
    {
        "ticker": "217480",
        "name": "에스디생명공학",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 화학제품 제조업",
        "products": "마스크팩, 기초화장품",
    },
    {
        "ticker": "036180",
        "name": "지더블유바이텍",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기계장비 및 관련 물품 도매업",
        "products": "무선통신,방송및응용장치제조업",
    },
    {
        "ticker": "002410",
        "name": "범양건영",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "건물 건설업",
        "products": "토목공사,주택건설,건축공사,난방공사,전기공사,포장공사",
    },
    {
        "ticker": "294090",
        "name": "이오플로우",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "의료용 기기 제조업",
        "products": "웨어러블 인슐린펌프",
    },
    {
        "ticker": "096610",
        "name": "알에프세미",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "반도체 제조업",
        "products": "ECM Chip, TVS Diode, Driver IC, LED Module, LED",
    },
    {
        "ticker": "010600",
        "name": "웰바이오텍",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "상품 중개업",
        "products": "피혁의류 도,소매,의류 판매,수입,피혁(GRAIN LEATHER) 제조",
    },
    {
        "ticker": "298060",
        "name": "에스씨엠생명과학",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "의약품 제조업",
        "products": "세포치료제",
    },
    {
        "ticker": "900110",
        "name": "이스트아시아홀딩스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 금융업",
        "products": "스포츠화, 스포츠의류",
    },
    {
        "ticker": "082660",
        "name": "코스나인",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 화학제품 제조업",
        "products": "화장품",
    },
    {
        "ticker": "357430",
        "name": "마스턴프리미어리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "프랑스 파리 소재 크리스탈파크, 프랑스 아마존 라스트마일 물류센터, 인천 항동 스마트물류센터",
    },
    {
        "ticker": "145270",
        "name": "케이탑리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "부동산 임대",
    },
    {
        "ticker": "036690",
        "name": "코맥스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "통신 및 방송 장비 제조업",
        "products": "홈네트워크시스템,CCTV 방송설비",
    },
    {
        "ticker": "418250",
        "name": "시큐레터",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "소프트웨어 개발 및 공급업",
        "products": "SLE(이메일 보안), SLF(파일 보안)",
    },
    {
        "ticker": "900310",
        "name": "컬러레이",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 금융업",
        "products": "화장품용 진주광택안료",
    },
    {
        "ticker": "123840",
        "name": "뉴온",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "특수 목적용 기계 제조업",
        "products": "진공장비",
    },
    {
        "ticker": "900270",
        "name": "헝셩그룹",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 금융업",
        "products": "자회사 제품 : 아동용 완구 및 아동복 등",
    },
    {
        "ticker": "049180",
        "name": "셀루메드",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기초 의약물질 제조업",
        "products": "의료기기, 바이오시밀러 및 헬스케어사업",
    },
    {
        "ticker": "117670",
        "name": "알파칩스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "반도체 제조업",
        "products": "시스템 반도체 개발",
    },
    {
        "ticker": "005030",
        "name": "부산주공",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "자동차 신품 부품 제조업",
        "products": "자동차부품(엔진부품,조향장치부품,브레이장치부품,오토미셧부품) 제조,도매/부동산 임대",
    },
    {
        "ticker": "900100",
        "name": "애머릿지",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "자동차 부품 및 내장품 판매업",
        "products": "인터모달 신생 및 재생타이어",
    },
    {
        "ticker": "074610",
        "name": "이엔플러스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "일반 목적용 기계 제조업",
        "products": "소방자동차 제조",
    },
    {
        "ticker": "900260",
        "name": "로스웰",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 금융업",
        "products": "CAN Control Gateway, CAN기능모듈, BCM 차체제어모듈",
    },
    {
        "ticker": "196490",
        "name": "디에이테크놀로지",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "특수 목적용 기계 제조업",
        "products": "2차전지설비",
    },
    {
        "ticker": "001840",
        "name": "이화공영",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "건물 건설업",
        "products": "도급공사",
    },
    {
        "ticker": "284620",
        "name": "카이노스메드",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "자연과학 및 공학 연구개발업",
        "products": "기업인수합병",
    },
    {
        "ticker": "900300",
        "name": "오가닉티코스메틱",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 금융업",
        "products": "유아용 화장품(클렌징, 여름용, 피부케어, 기능성 화장품)",
    },
    {
        "ticker": "068940",
        "name": "셀피글로벌",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "전자부품 제조업",
        "products": "신용카드 및 전자화폐 등",
    },
    {
        "ticker": "219550",
        "name": "디와이디",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "생활용품 도매업",
        "products": "화장품 유통",
    },
    {
        "ticker": "405000",
        "name": "플라즈맵",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "의료용 기기 제조업",
        "products": "플라즈마 멸균기 및 표면처리기기",
    },
    {
        "ticker": "001140",
        "name": "국보",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "도로 화물 운송업",
        "products": "화물자동차운송,콘테이너운송,수출입화물보관,도로운송,CY보관,하역",
    },
    {
        "ticker": "246250",
        "name": "에스엘에스바이오",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "그외 기타 전문, 과학 및 기술 서비스업",
        "products": "의약품 품질관리, 신약개발지원, 체외진단기기",
    },
    {
        "ticker": "052770",
        "name": "아이톡시",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "소프트웨어 개발 및 공급업",
        "products": "게임",
    },
    {
        "ticker": "043220",
        "name": "티에스넥스젠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "특수 목적용 기계 제조업",
        "products": "발전설비 Damper, 전력설비 Busway",
    },
    {
        "ticker": "217620",
        "name": "선샤인푸드",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "음식점업",
        "products": "직영음식점, 축산물가공, 프랜차이즈",
    },
    {
        "ticker": "005110",
        "name": "한창",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기계장비 및 관련 물품 도매업",
        "products": "소화기, 통신장비 유통",
    },
    {
        "ticker": "002210",
        "name": "동성제약",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "의약품 제조업",
        "products": "의약품,화장품 제조,도매",
    },
    {
        "ticker": "145210",
        "name": "다이나믹디자인",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "특수 목적용 기계 제조업",
        "products": "타이어 금형, 타이어 제조설비",
    },
    {
        "ticker": "139050",
        "name": "BF랩스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "컴퓨터 프로그래밍, 시스템 통합 및 관리업",
        "products": "용역서비스(ITS,BIS,ATMS,BRT)",
    },
    {
        "ticker": "900070",
        "name": "글로벌에스엠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 금융업",
        "products": "자회사 제품 : IT기기용 정밀 화스너부품(스크류, 샤프트, 스프링)",
    },
    {
        "ticker": "204630",
        "name": "스튜디오산타클로스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "창작 및 예술관련 서비스업",
        "products": "창작 및 예술관련 서비스업",
    },
    {
        "ticker": "065150",
        "name": "대산F&B",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "음·식료품 및 담배 도매업",
        "products": "외식프랜차이즈사업,육류가공,식자재유통등",
    },
    {
        "ticker": "258830",
        "name": "세종메디칼",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "의료용 기기 제조업",
        "products": "복강경수술용 투관침 등",
    },
    {
        "ticker": "080720",
        "name": "한국유니온제약",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "의약품 제조업",
        "products": "항생제, 순환기계, 근골격계, 소화기계류 완제의약품",
    },
    {
        "ticker": "230980",
        "name": "비유테크놀러지",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "소프트웨어 개발 및 공급업",
        "products": "VR기반 교육훈련용솔루션",
    },
    {
        "ticker": "900120",
        "name": "씨엑스아이",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 금융업",
        "products": "건강보조식품",
    },
    {
        "ticker": "241820",
        "name": "피씨엘",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "의료용품 및 기타 의약 관련제품 제조업",
        "products": "다중 체외진단 제품, 플랫폼서비스",
    },
    {
        "ticker": "009440",
        "name": "KC그린홀딩스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 금융업",
        "products": "기타금융업",
    },
    {
        "ticker": "152550",
        "name": "한국ANKOR유전",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "신탁업 및 집합투자업",
        "products": "None",
    },
    {
        "ticker": "204210",
        "name": "스타에스엠리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "호텔 부동산 취득, 관리, 개량 및 처분",
    },
    {
        "ticker": "106520",
        "name": "노블엠앤비",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "사진장비 및 광학기기 제조업",
        "products": "차량용 카메라렌즈 및 프로젝션광학모듈렌즈",
    },
    {
        "ticker": "092600",
        "name": "앤씨앤",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "반도체 제조업",
        "products": "차량용 블랙박스 / 영상처리용 시스템반도체",
    },
    {
        "ticker": "227100",
        "name": "퀀텀온",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 관련 서비스업",
        "products": "스마트 액세서리(보조배터리 등)",
    },
    {
        "ticker": "027040",
        "name": "서울전자통신",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업",
        "products": "전자변성기, 무역업(트랜스포머자재)",
    },
    {
        "ticker": "140910",
        "name": "에이리츠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "부동산 임대 및 공급업",
        "products": "None",
    },
    {
        "ticker": "352770",
        "name": "셀레스트라",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "의료용품 및 기타 의약 관련제품 제조업",
        "products": "Geno Series, CD-PRIME, Cancer Prime",
    },
    {
        "ticker": "032980",
        "name": "바이온",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "음·식료품 및 담배 도매업",
        "products": "배너,타포린,화장품,자동차부품",
    },
    {
        "ticker": "030350",
        "name": "드래곤플라이",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "소프트웨어 개발 및 공급업",
        "products": "온라인게임",
    },
    {
        "ticker": "054630",
        "name": "에이디칩스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "그외 기타 제품 제조업",
        "products": "업소용냉동냉장, 반도체칩",
    },
    {
        "ticker": "065570",
        "name": "삼영이엔씨",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "통신 및 방송 장비 제조업",
        "products": "GMDSS장비, GPS플로터 등",
    },
    {
        "ticker": "174880",
        "name": "장원테크",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "통신 및 방송 장비 제조업",
        "products": "스마트폰 및 태블릿PC Bracket",
    },
    {
        "ticker": "244460",
        "name": "올리패스",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기초 의약물질 제조업",
        "products": "인공유전자 플랫폼(OliPass PNA) 기술을 활용한 RNA치료제 신약개발",
    },
    {
        "ticker": "079970",
        "name": "투비소프트",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "소프트웨어 개발 및 공급업",
        "products": "MiPlatform, X Platform",
    },
    {
        "ticker": "060240",
        "name": "스타코링크",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "선박 및 보트 건조업",
        "products": "모바일게임(열혈강호,검과마법)",
    },
    {
        "ticker": "101390",
        "name": "아이엠",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "전자부품 제조업",
        "products": "휴대폰카메라모듈 등",
    },
    {
        "ticker": "043090",
        "name": "더테크놀로지",
        "sectorCode": "__sectorCode__",
        "industryCode": "__industryCode__",
        "KRXIndustry": "기타 전문 도매업",
        "products": "바이오리엑터(Bioreactor, 생물반응기)",
    },
]